/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/appointments': RouteRecordInfo<
      '/admin/appointments',
      '/admin/appointments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/cars': RouteRecordInfo<
      '/admin/cars',
      '/admin/cars',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/dashboard': RouteRecordInfo<
      '/admin/dashboard',
      '/admin/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/users': RouteRecordInfo<
      '/admin/users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/regristreren': RouteRecordInfo<
      '/regristreren',
      '/regristreren',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/dashboard': RouteRecordInfo<
      '/user/dashboard',
      '/user/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/admin/appointments.vue': {
      routes:
        | '/admin/appointments'
      views:
        | never
    }
    'src/pages/admin/cars.vue': {
      routes:
        | '/admin/cars'
      views:
        | never
    }
    'src/pages/admin/dashboard.vue': {
      routes:
        | '/admin/dashboard'
      views:
        | never
    }
    'src/pages/admin/users.vue': {
      routes:
        | '/admin/users'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/regristreren.vue': {
      routes:
        | '/regristreren'
      views:
        | never
    }
    'src/pages/user/dashboard.vue': {
      routes:
        | '/user/dashboard'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
