/* tslint:disable */
/* eslint-disable */
/**
 * jascarwash API
 * API for jascarwash
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FullCarData
 */
export interface FullCarData {
    /**
     * 
     * @type {string}
     * @memberof FullCarData
     */
    license_plate: string;
    /**
     * 
     * @type {string}
     * @memberof FullCarData
     */
    make: string;
    /**
     * 
     * @type {string}
     * @memberof FullCarData
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof FullCarData
     */
    vehicle_type: string;
    /**
     * 
     * @type {string}
     * @memberof FullCarData
     */
    color: string;
    /**
     * 
     * @type {string}
     * @memberof FullCarData
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof FullCarData
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof FullCarData
     */
    notes: string | null;
    /**
     * 
     * @type {string}
     * @memberof FullCarData
     */
    owner_id: string | null;
}

/**
 * Check if a given object implements the FullCarData interface.
 */
export function instanceOfFullCarData(value: object): value is FullCarData {
    if (!('license_plate' in value) || value['license_plate'] === undefined) return false;
    if (!('make' in value) || value['make'] === undefined) return false;
    if (!('model' in value) || value['model'] === undefined) return false;
    if (!('vehicle_type' in value) || value['vehicle_type'] === undefined) return false;
    if (!('color' in value) || value['color'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('created_at' in value) || value['created_at'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('owner_id' in value) || value['owner_id'] === undefined) return false;
    return true;
}

export function FullCarDataFromJSON(json: any): FullCarData {
    return FullCarDataFromJSONTyped(json, false);
}

export function FullCarDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullCarData {
    if (json == null) {
        return json;
    }
    return {
        
        'license_plate': json['license_plate'],
        'make': json['make'],
        'model': json['model'],
        'vehicle_type': json['vehicle_type'],
        'color': json['color'],
        'id': json['id'],
        'created_at': (new Date(json['created_at'])),
        'notes': json['notes'],
        'owner_id': json['owner_id'],
    };
}

export function FullCarDataToJSON(json: any): FullCarData {
    return FullCarDataToJSONTyped(json, false);
}

export function FullCarDataToJSONTyped(value?: FullCarData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'license_plate': value['license_plate'],
        'make': value['make'],
        'model': value['model'],
        'vehicle_type': value['vehicle_type'],
        'color': value['color'],
        'id': value['id'],
        'created_at': value['created_at'].toISOString(),
        'notes': value['notes'],
        'owner_id': value['owner_id'],
    };
}

