/* tslint:disable */
/* eslint-disable */
/**
 * jascarwash API
 * API for jascarwash
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoutReturn
 */
export interface LogoutReturn {
    /**
     * 
     * @type {string}
     * @memberof LogoutReturn
     */
    message: string;
}

/**
 * Check if a given object implements the LogoutReturn interface.
 */
export function instanceOfLogoutReturn(value: object): value is LogoutReturn {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LogoutReturnFromJSON(json: any): LogoutReturn {
    return LogoutReturnFromJSONTyped(json, false);
}

export function LogoutReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutReturn {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function LogoutReturnToJSON(json: any): LogoutReturn {
    return LogoutReturnToJSONTyped(json, false);
}

export function LogoutReturnToJSONTyped(value?: LogoutReturn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

