/* tslint:disable */
/* eslint-disable */
/**
 * jascarwash API
 * API for jascarwash
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NumberplateData
 */
export interface NumberplateData {
    /**
     * 
     * @type {string}
     * @memberof NumberplateData
     */
    kenteken: string;
    /**
     * 
     * @type {string}
     * @memberof NumberplateData
     */
    merk: string;
    /**
     * 
     * @type {string}
     * @memberof NumberplateData
     */
    handelsbenaming: string;
}

/**
 * Check if a given object implements the NumberplateData interface.
 */
export function instanceOfNumberplateData(value: object): value is NumberplateData {
    if (!('kenteken' in value) || value['kenteken'] === undefined) return false;
    if (!('merk' in value) || value['merk'] === undefined) return false;
    if (!('handelsbenaming' in value) || value['handelsbenaming'] === undefined) return false;
    return true;
}

export function NumberplateDataFromJSON(json: any): NumberplateData {
    return NumberplateDataFromJSONTyped(json, false);
}

export function NumberplateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberplateData {
    if (json == null) {
        return json;
    }
    return {
        
        'kenteken': json['kenteken'],
        'merk': json['merk'],
        'handelsbenaming': json['handelsbenaming'],
    };
}

export function NumberplateDataToJSON(json: any): NumberplateData {
    return NumberplateDataToJSONTyped(json, false);
}

export function NumberplateDataToJSONTyped(value?: NumberplateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'kenteken': value['kenteken'],
        'merk': value['merk'],
        'handelsbenaming': value['handelsbenaming'],
    };
}

