/* tslint:disable */
/* eslint-disable */
/**
 * jascarwash API
 * API for jascarwash
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordHashReturn
 */
export interface PasswordHashReturn {
    /**
     * 
     * @type {string}
     * @memberof PasswordHashReturn
     */
    hashed_password: string;
}

/**
 * Check if a given object implements the PasswordHashReturn interface.
 */
export function instanceOfPasswordHashReturn(value: object): value is PasswordHashReturn {
    if (!('hashed_password' in value) || value['hashed_password'] === undefined) return false;
    return true;
}

export function PasswordHashReturnFromJSON(json: any): PasswordHashReturn {
    return PasswordHashReturnFromJSONTyped(json, false);
}

export function PasswordHashReturnFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordHashReturn {
    if (json == null) {
        return json;
    }
    return {
        
        'hashed_password': json['hashed_password'],
    };
}

export function PasswordHashReturnToJSON(json: any): PasswordHashReturn {
    return PasswordHashReturnToJSONTyped(json, false);
}

export function PasswordHashReturnToJSONTyped(value?: PasswordHashReturn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hashed_password': value['hashed_password'],
    };
}

