/* tslint:disable */
/* eslint-disable */
/**
 * jascarwash API
 * API for jascarwash
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    full_name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    hashed_password: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    disabled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    created_at?: Date;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    permissions?: number;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('hashed_password' in value) || value['hashed_password'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'],
        'full_name': json['full_name'] == null ? undefined : json['full_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'hashed_password': json['hashed_password'],
        'disabled': json['disabled'] == null ? undefined : json['disabled'],
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'full_name': value['full_name'],
        'email': value['email'],
        'hashed_password': value['hashed_password'],
        'disabled': value['disabled'],
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'permissions': value['permissions'],
    };
}

