# build stage
FROM node:24.6.0-alpine3.22 AS build
WORKDIR /app

# copy dependency files first (better for caching)
COPY src/package*.json ./
RUN npm install

# copy the rest of the frontend source
COPY src/ .

# build the app
RUN npm run build

# serve stage
FROM nginx:alpine3.22
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
