/* tslint:disable */
/* eslint-disable */
/**
 * jascarwash API
 * API for jascarwash
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  LogoutReturn,
  PasswordHashReturn,
  User,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    LogoutReturnFromJSON,
    LogoutReturnToJSON,
    PasswordHashReturnFromJSON,
    PasswordHashReturnToJSON,
    UserFromJSON,
    UserToJSON,
} from '../models/index';

export interface ChangePasswordAuthChangePasswordPostRequest {
    password: string;
    username?: string | null;
}

export interface ChangePermissionsAuthChangePermissionsPostRequest {
    username: string;
    permissions: number;
}

export interface DisableUserAuthDisableUserPostRequest {
    username: string;
}

export interface EnableUserAuthEnableUserPostRequest {
    username: string;
}

export interface GenerateHashAuthGenerateHashPostRequest {
    password: any;
}

export interface GetUserInfoAuthUserUsernameGetRequest {
    username: string;
}

export interface LoginForAccessTokenAuthLoginPostRequest {
    username: string;
    password: string;
}

export interface RegisterUserAuthRegisterPostRequest {
    username: string;
    password: string;
    fullName?: string | null;
    email?: string | null;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Change Password
     */
    async changePasswordAuthChangePasswordPostRaw(requestParameters: ChangePasswordAuthChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling changePasswordAuthChangePasswordPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/change-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Change Password
     */
    async changePasswordAuthChangePasswordPost(requestParameters: ChangePasswordAuthChangePasswordPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.changePasswordAuthChangePasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change Permissions
     */
    async changePermissionsAuthChangePermissionsPostRaw(requestParameters: ChangePermissionsAuthChangePermissionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling changePermissionsAuthChangePermissionsPost().'
            );
        }

        if (requestParameters['permissions'] == null) {
            throw new runtime.RequiredError(
                'permissions',
                'Required parameter "permissions" was null or undefined when calling changePermissionsAuthChangePermissionsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        if (requestParameters['permissions'] != null) {
            queryParameters['permissions'] = requestParameters['permissions'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/change-permissions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Change Permissions
     */
    async changePermissionsAuthChangePermissionsPost(requestParameters: ChangePermissionsAuthChangePermissionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.changePermissionsAuthChangePermissionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Disable User
     */
    async disableUserAuthDisableUserPostRaw(requestParameters: DisableUserAuthDisableUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling disableUserAuthDisableUserPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/disable-user`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Disable User
     */
    async disableUserAuthDisableUserPost(requestParameters: DisableUserAuthDisableUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.disableUserAuthDisableUserPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Enable User
     */
    async enableUserAuthEnableUserPostRaw(requestParameters: EnableUserAuthEnableUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling enableUserAuthEnableUserPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/enable-user`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Enable User
     */
    async enableUserAuthEnableUserPost(requestParameters: EnableUserAuthEnableUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.enableUserAuthEnableUserPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Generate Hash
     */
    async generateHashAuthGenerateHashPostRaw(requestParameters: GenerateHashAuthGenerateHashPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasswordHashReturn>> {
        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling generateHashAuthGenerateHashPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/generate-hash`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasswordHashReturnFromJSON(jsonValue));
    }

    /**
     * Generate Hash
     */
    async generateHashAuthGenerateHashPost(requestParameters: GenerateHashAuthGenerateHashPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasswordHashReturn> {
        const response = await this.generateHashAuthGenerateHashPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get User Info
     */
    async getUserInfoAuthUserUsernameGetRaw(requestParameters: GetUserInfoAuthUserUsernameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling getUserInfoAuthUserUsernameGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/user/{username}`;
        urlPath = urlPath.replace(`{${"username"}}`, encodeURIComponent(String(requestParameters['username'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get User Info
     */
    async getUserInfoAuthUserUsernameGet(requestParameters: GetUserInfoAuthUserUsernameGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getUserInfoAuthUserUsernameGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Users
     */
    async listUsersAuthListUsersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<User>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/list-users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserFromJSON));
    }

    /**
     * List Users
     */
    async listUsersAuthListUsersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<User>> {
        const response = await this.listUsersAuthListUsersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Login For Access Token
     */
    async loginForAccessTokenAuthLoginPostRaw(requestParameters: LoginForAccessTokenAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling loginForAccessTokenAuthLoginPost().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling loginForAccessTokenAuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Login For Access Token
     */
    async loginForAccessTokenAuthLoginPost(requestParameters: LoginForAccessTokenAuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.loginForAccessTokenAuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logout
     */
    async logoutAuthLogoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LogoutReturn>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LogoutReturnFromJSON(jsonValue));
    }

    /**
     * Logout
     */
    async logoutAuthLogoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LogoutReturn> {
        const response = await this.logoutAuthLogoutPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Register User
     */
    async registerUserAuthRegisterPostRaw(requestParameters: RegisterUserAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['username'] == null) {
            throw new runtime.RequiredError(
                'username',
                'Required parameter "username" was null or undefined when calling registerUserAuthRegisterPost().'
            );
        }

        if (requestParameters['password'] == null) {
            throw new runtime.RequiredError(
                'password',
                'Required parameter "password" was null or undefined when calling registerUserAuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['username'] != null) {
            queryParameters['username'] = requestParameters['username'];
        }

        if (requestParameters['password'] != null) {
            queryParameters['password'] = requestParameters['password'];
        }

        if (requestParameters['fullName'] != null) {
            queryParameters['full_name'] = requestParameters['fullName'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Register User
     */
    async registerUserAuthRegisterPost(requestParameters: RegisterUserAuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.registerUserAuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Who Is Current User
     */
    async whoIsCurrentUserAuthWhoamiGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/whoami`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
    }

    /**
     * Who Is Current User
     */
    async whoIsCurrentUserAuthWhoamiGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
        const response = await this.whoIsCurrentUserAuthWhoamiGetRaw(initOverrides);
        return await response.value();
    }

}
