/* tslint:disable */
/* eslint-disable */
/**
 * jascarwash API
 * API for jascarwash
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  NumberplateData,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    NumberplateDataFromJSON,
    NumberplateDataToJSON,
} from '../models/index';

export interface GetNumberplateV1NumberplateNumberplateGetRequest {
    numberplate: string;
}

/**
 * 
 */
export class V1Api extends runtime.BaseAPI {

    /**
     * Get Numberplate
     */
    async getNumberplateV1NumberplateNumberplateGetRaw(requestParameters: GetNumberplateV1NumberplateNumberplateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NumberplateData>>> {
        if (requestParameters['numberplate'] == null) {
            throw new runtime.RequiredError(
                'numberplate',
                'Required parameter "numberplate" was null or undefined when calling getNumberplateV1NumberplateNumberplateGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/numberplate/{numberplate}`;
        urlPath = urlPath.replace(`{${"numberplate"}}`, encodeURIComponent(String(requestParameters['numberplate'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NumberplateDataFromJSON));
    }

    /**
     * Get Numberplate
     */
    async getNumberplateV1NumberplateNumberplateGet(requestParameters: GetNumberplateV1NumberplateNumberplateGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NumberplateData>> {
        const response = await this.getNumberplateV1NumberplateNumberplateGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Sorttypes
     */
    async getSortTypesV1GetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Sorttypes
     */
    async getSortTypesV1Get(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSortTypesV1GetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get Sorttypes
     */
    async getSortTypesV1Get_1Raw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Sorttypes
     */
    async getSortTypesV1Get_1(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getSortTypesV1Get_1Raw(initOverrides);
        return await response.value();
    }

    /**
     * Needadmin
     */
    async needAdminV1NeedAdminGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/needAdmin`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Needadmin
     */
    async needAdminV1NeedAdminGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.needAdminV1NeedAdminGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Needauth
     */
    async needAuthV1NeedAuthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/needAuth`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Needauth
     */
    async needAuthV1NeedAuthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.needAuthV1NeedAuthGetRaw(initOverrides);
        return await response.value();
    }

}
